### ISSUE TITLE
dependencies vs dev-dependencies 

### ISSUE THREAD

**Issue by NouraldinS** [FACG5/CurrencyExchange#10]
```json
  "dependencies": {},
  "devDependencies": {
    "request": "^2.87.0",
    "supertest": "^3.1.0",
    "tap-spec": "^5.0.0",
    "tape": "^4.9.1"
  },
```
So this is what you have. Would your website work without tape? Sure, without tap-spec? Absolutely, without supertest? yes, without request? I don't think so.
Decide whether a dependency is a dev or not after answering this question: "Would my website work without this dep?" If yes, then it's a dep, otherwise, it's dev.

**Comment by ahmad1091** [comment]
We will consider it next time
