### ISSUE TITLE
Summary: Fix indentation and structure

### ISSUE THREAD

**Issue by NouraldinS** [FACG5/CurrencyExchange#11]
Your website is functional, your tests are working, you're on heroku. Everything works well. But I'd hoped to see you loving your code even more, go that extra mile, and feel pain when seeing distorted indentation. I would've rated this repo much better if you'd already gone that extra mile. Please consider to, @OnsNader @ahmad1091 .

**Comment by ahmad1091** [comment]
Thank you for time we will consider every note you mentioned next projects
