### ISSUE TITLE
Initial issues

### ISSUE THREAD

**Issue by NouraldinS** [FACG5/CurrencyExchange#5]
You should've had initial issues set up for your project like this:
![image](https://user-images.githubusercontent.com/28482442/43546084-64888a32-95e0-11e8-8792-a1f416266968.png)
This gives you better understanding of where you're going and what to do next.

**Comment by ahmad1091** [comment]
You are right ,we will  consider it i the next project.

**Comment by ahmad1091** [comment]
You are right ,we will consider it i the next project.
