### ISSUE TITLE
While testing

### ISSUE THREAD

**Issue by NouraldinS** [FACG5/CurrencyExchange#6]
https://github.com/FACG5/CurrencyExchange/blob/bda57ad68de2b8e9e697c358142a587a8e55f252/test/test.js#L6
You don't need to check that 2 is actually equal to 2, and although the rest of your test cases are sufficient, I didn't quite understand the `sssss` description for your last test.

**Comment by ahmad1091** [comment]
We did it to check if the test work and we forget to delete it.
