### ISSUE TITLE
Fix indentation

### ISSUE THREAD

**Issue by NouraldinS** [FACG5/CurrencyExchange#7]
Your `test.js`'s, `handler.js`'s indentation is completely out of order, as well as your `html`. And other files as well.
`if (it_works) make_it_better();`

+ Add a new line after your requires.
+ Add a new line between every test and the test after.
+ Use indentation of 2, 4 or 6, not all 3 of them.
+ Use semicolons always or never.
+ Either use single quotation `' '` or double quotation `" "`, not mixed.
+ Add spaces after `{` and before `}`.
+ Use `const` when your variable is going to sustain a fixed value.
+ Add a space after the commas `,` but not before them.

**Comment by ahmad1091** [comment]
We fix it
